
# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  post:
      categories: /categories
      archives: /archives
      tags: /tags
  # project: /project
  # search: /search
  # about: http://www.example.com
  # rss: /atom.xml

# Miscelaneous
favicon: favicon.png
logo: 

share:
    show: false
    img:
    img_alt:
    tip_text: test

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/xoxo.css

# baidu url js push
baidu_url_js_push: true


# comment extend, support gialk, giscus
# giscus https://giscus.app/zh-CN
comment_extend:
    gitalk:
        enable: false
        owner: Github username
        repo: issue repo name
        admin: github username
        clientID: xxx
        clientSecret: xxx
    giscus:
        enable: true
        repo: Glooory/Glooory.github.io
        repoId: R_kgDOLfptWw
        dataCategoryId: DIC_kwDOLfptW84Cd-9M
        dataMapping: pathname 
        dataReactionsEnabled: true
        dataInputPosition: top

# scripts loaded in the end of the body
scripts:
#- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/xoxo.js

# switch
show_excerpt: true
show_date: true

#footer
index_page: https://github.com/glooory
main_site: https://github.com/glooory
github: https://github.com/glooory
links_url: /links

# 友情链接
links:
  # example: https://www.example.com

# project
projects:
  # hexo-theme-xoxo-plus:
  #   url: https://github.com/example/xxxx
  #   descript: a hexo theme
